#!/bin/bash
HUBSINGESTPATH=${BIOC_HUBSINGEST_PATH:-/usr/local/bin/hubsingest}

case "$1" in
  create_endpoint)
    shift
    bash $HUBSINGESTPATH/scripts/hubsingest_create_endpoint.sh "$@"
    ;;
  delete_endpoint)
    shift
    bash $HUBSINGESTPATH/scripts/hubsingest_delete_endpoint.sh "$@"
    ;;
  test_endpoint)
    shift
    bash $HUBSINGESTPATH/scripts/hubsingest_test_endpoint.sh "$@"
    ;;
  launch_rstudio)
    shift
    bash $HUBSINGESTPATH/scripts/hubsingest_launch_rstudio.sh "$@"
    ;;
  scan_data)
    shift
    bash $HUBSINGESTPATH/scripts/hubsingest_scan_data.sh "$@"
    ;;
  *)
    echo "Usage: hubsingest {create_endpoint|delete_endpoint|test_endpoint|launch_rstudio|scan_data} [options]"
    exit 1
    ;;
esac
