#!/bin/bash
HUBSINGESTPATH=${BIOC_HUBSINGEST_PATH:-/usr/local/bin/hubsingest}

case "$1" in
  create_endpoint)
    shift
    bash $HUBSINGESTPATH/scripts/hubsingest_create_endpoint.sh "$@"
    ;;
  delete_endpoint)
    shift
    bash $HUBSINGESTPATH/scripts/hubsingest_delete_endpoint.sh "$@"
    ;;
  test_endpoint)
    shift
    bash $HUBSINGESTPATH/scripts/hubsingest_test_endpoint.sh "$@"
    ;;
  *)
    echo "Usage: hubsingest {create_endpoint|delete_endpoint|test_endpoint} [options]"
    exit 1
    ;;
esac
