name: Delete Hub Ingest Endpoint

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username of the endpoint to delete'
        required: true
        type: string

env:
  BIOC_HUBSINGEST_PATH: "${{ github.workspace }}"

jobs:
  delete-endpoint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: save kubeconfig
        shell: bash
        run: mkdir -p ~/.kube && echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      
      - name: Install Kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.24.4/bin/linux/amd64/kubectl" && \
          chmod +x ./kubectl && \
          sudo mv ./kubectl /usr/local/bin/kubectl && \
          kubectl version
      
      - name: Delete endpoint
        run: |
          USERNAME_LOWER=$(echo "${{ inputs.username }}" | tr '[:upper:]' '[:lower:]')
          sudo bash install_hubsingest.sh
          export PATH="$PATH:$BIOC_HUBSINGEST_PATH"
          hubsingest delete_endpoint "${USERNAME_LOWER}"
